import * as Utils from 'causal-net.utils';
import * as Log from 'causal-net.log';
// import * as Storage from 'causal-net.storage';
import * as Preprocessing from 'causal-net.preprocessing';
import * as Memory from 'causal-net.memory';
import { causalNetCore } from 'causal-net.core';
import { causalNetSGDOptimizer } from 'causal-net.optimizers';
import { causalNetModels } from "causal-net.models";
import * as Sampling from 'causal-net.sampling';
import * as Representation from 'causal-net.representation';
import * as fs from 'fs';
var R = causalNetCore.CoreFunction;
var T = causalNetCore.CoreTensor;
var { Loss } = causalNetModels.skipGram();
var { Stream } = Utils;
var { termLogger } = Log;
// var { indexDBStorage } = Storage;
var { nlpPreprocessing } = Preprocessing;
var { causalNetMemory } = Memory;
var { causalNetSampling } = Sampling; 
var { CSV, Fetch } = Utils;
var { SentenceEncode, causalNetWordVec } = Representation;
var optimizers = causalNetSGDOptimizer;
var enWV = causalNetWordVec.EN;
var fetch = Fetch.fetch;